export const membersData = [
  {
    email: "buddy@test.com",
    username: "buddy_the_dog",
    gender: "male",
    dateOfBirth: "2017-03-10",
    name: "Buddy",
    created: "2020-08-12",
    lastActive: "2020-09-02",
    description:
      "Energetic and playful, Buddy loves chasing tennis balls and is always eager for belly rubs. He's great with kids and enjoys long walks in the park.\r\n",
    city: "Barksville",
    country: "United States",
    image: "/images/dog1.jpeg",
  },
  {
    email: "bella@test.com",
    username: "bella_girl",
    gender: "female",
    dateOfBirth: "2018-11-15",
    name: "Bella",
    created: "2021-01-05",
    lastActive: "2021-02-10",
    description:
      "Bella is a calm and friendly companion who loves lounging by the fireplace. Her gentle nature makes her a favorite in the neighborhood.\r\n",
    city: "Puptown",
    country: "Canada",
    image: "/images/dog2.jpeg",
  },
  {
    email: "max@test.com",
    username: "max_the_dog",
    gender: "male",
    dateOfBirth: "2016-06-07",
    name: "Max",
    created: "2019-05-18",
    lastActive: "2019-06-12",
    description:
      "Max is a protector at heart, always alert and keeping an eye on his family. Despite his serious demeanor, he loves a good game of fetch.\r\n",
    city: "Tailwag",
    country: "Australia",
    image: "/images/dog3.jpeg",
  },
  {
    email: "daisy@test.com",
    username: "daisy_doggo",
    gender: "female",
    dateOfBirth: "2019-04-22",
    name: "Daisy",
    created: "2021-03-12",
    lastActive: "2021-03-25",
    description:
      "Daisy is a curious and adventurous dog who loves exploring new trails. She enjoys meeting other dogs and sniffing every tree she passes.\r\n",
    city: "Pawville",
    country: "New Zealand",
    image: "/images/dog4.jpeg",
  },
  {
    email: "charlie@test.com",
    username: "charlie_boy",
    gender: "male",
    dateOfBirth: "2015-09-29",
    name: "Charlie",
    created: "2020-11-22",
    lastActive: "2020-12-10",
    description:
      "Charlie is a laid-back pup who enjoys snoozing in the sun. His favorite hobby is napping after a hearty meal.\r\n",
    city: "Furrytown",
    country: "United Kingdom",
    image: "/images/dog5.jpeg",
  },
  {
    email: "molly@test.com",
    username: "molly_girl",
    gender: "female",
    dateOfBirth: "2018-02-19",
    name: "Molly",
    created: "2021-04-30",
    lastActive: "2021-05-15",
    description:
      "Molly is always the life of the party, greeting everyone she meets with a wagging tail. She loves socializing and playing tug-of-war.\r\n",
    city: "Barkburg",
    country: "Ireland",
    image: "/images/dog6.jpeg",
  },
  {
    email: "rocky@test.com",
    username: "rocky_the_boss",
    gender: "male",
    dateOfBirth: "2017-12-05",
    name: "Rocky",
    created: "2020-02-14",
    lastActive: "2020-03-10",
    description:
      "Rocky is a strong and determined dog who loves challenges. He’s always eager to learn new tricks and impress his owners with his intelligence.\r\n",
    city: "Dogtown",
    country: "South Africa",
    image: "/images/dog7.jpeg",
  },
  {
    email: "lola@test.com",
    username: "lola_love",
    gender: "female",
    dateOfBirth: "2019-08-21",
    name: "Lola",
    created: "2021-07-19",
    lastActive: "2021-08-01",
    description:
      "Lola is a cuddle bug, always seeking attention and belly rubs. She’s happiest when snuggling on the couch with her favorite human.\r\n",
    city: "Barksdale",
    country: "Brazil",
    image: "/images/dog8.jpeg",
  },
  {
    email: "bentley@test.com",
    username: "bentley_boy",
    gender: "male",
    dateOfBirth: "2016-03-14",
    name: "Bentley",
    created: "2020-06-30",
    lastActive: "2020-07-12",
    description:
      "Bentley is a refined dog with a taste for the finer things in life. He enjoys leisurely strolls and gourmet dog treats.\r\n",
    city: "Furr City",
    country: "Germany",
    image: "/images/dog9.jpeg",
  },
  {
    email: "sophie@test.com",
    username: "sophie_girl",
    gender: "female",
    dateOfBirth: "2018-10-01",
    name: "Sophie",
    created: "2021-05-28",
    lastActive: "2021-06-05",
    description:
      "Sophie is always curious, sticking her nose into every corner of the house. Her inquisitive nature makes her a great little detective.\r\n",
    city: "Dogwood",
    country: "France",
    image: "/images/dog10.jpeg",
  },
  {
    email: "duke@test.com",
    username: "duke_dog",
    gender: "male",
    dateOfBirth: "2017-07-30",
    name: "Duke",
    created: "2019-12-08",
    lastActive: "2020-01-04",
    description:
      "Duke is a regal and noble dog who commands attention wherever he goes. He’s calm, confident, and loves basking in the sun.\r\n",
    city: "Pawtropolis",
    country: "Italy",
    image: "/images/dog11.jpeg",
  },
  {
    email: "zoey@test.com",
    username: "zoey_cute",
    gender: "female",
    dateOfBirth: "2019-05-09",
    name: "Zoey",
    created: "2021-03-18",
    lastActive: "2021-04-02",
    description:
      "Zoey is an energetic bundle of joy, always zipping around the yard and chasing after squirrels. She never runs out of energy.\r\n",
    city: "Barkington",
    country: "Japan",
    image: "/images/dog12.jpeg",
  },
];
